// packages/vue/src/components/TheInput.vue
<script setup lang="ts">
const modelValue = defineModel()
</script>

<template>
  <input
    id="input"
    v-model="modelValue"
    v-bind="$attrs"
    type="text"
    p="x-4 y-2"
    w="250px"
    text="center"
    bg="transparent"
    border="~ rounded gray-200 dark:gray-700"
    outline="none active:none"
  >
</template>

// packages/react/src/components/TheInput.tsx
export default function TheInput(props: React.JSX.IntrinsicElements['input']) {
  return (
    <input
      id="input"
      type="text"
      p="x-4 y-2"
      w="250px"
      text="center"
      bg="transparent"
      border="~ solid gray-200 rounded dark:gray-700"
      outline="none active:none"
      {...props}
    >
    </input>
  )
}
