// packages/react/src/pages/hi/[name].tsx
import { useTitle } from '@reactuses/core'
import { Link } from 'react-router'

function hi() {
  const navigate = useNavigate()
  const { savedName, otherNames, setNewName } = useUserStore()
  const params = useParams()
  useTitle(`Hi, ${params.name}!`)
  useEffect(() => setNewName(params.name!), [params.name])

  return (
    <div>
      <div i-carbon-pedestrian text-4xl inline-block />
      <p>
        Hi,
        {' '}
        {savedName}
      </p>

      <div text-sm op-75>
        Dynamic route!
      </div>

      {
        otherNames().length
          ? (
              <div mt-4 text-sm>
                <span op-75>Aka:</span>
                <ul>
                  {otherNames().map(otherName => (
                    <li key={otherName}>
                      <Link to={`/hi/${otherName}`} replace>
                        {otherName}
                      </Link>
                    </li>
                  ))}
                </ul>
              </div>
            )
          : ''
      }

      <div>
        <button className="m-3 text-sm btn mt-6" onClick={() => navigate(-1)}>
          Back
        </button>
      </div>
    </div>
  )
}

export default hi

// packages/vue/src/pages/hi/[name].vue
<script setup lang="ts">
const router = useRouter()
const route = useRoute('/hi/[name]')
const user = useUserStore()
watchEffect(() => {
  user.setNewName(route.params.name)
  useTitle(`Hi, ${route.params.name}!`)
})
</script>

<template>
  <div>
    <div i-carbon-pedestrian text-4xl inline-block />
    <p>
      Hi, {{ user.savedName }}
    </p>

    <p text-sm op-75>
      <em>Dynamic route!</em>
    </p>

    <template v-if="user.otherNames.length">
      <div mt-4 text-sm>
        <span op-75>Aka:</span>
        <ul>
          <li v-for="otherName in user.otherNames" :key="otherName">
            <RouterLink :to="`/hi/${otherName}`" replace>
              {{ otherName }}
            </RouterLink>
          </li>
        </ul>
      </div>
    </template>

    <div>
      <button m-3 mt-6 text-sm btn @click="router.back()">
        Back
      </button>
    </div>
  </div>
</template>
